openapi: 3.0.3
info:
  title: AdoptaPets API
  version: 1.0.0
  description: API para gestión de adopciones de mascotas

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: coderCookie
  
  responses:
    Unauthorized:
      description: No autenticado o token inválido
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            InvalidToken:
              value:
                status: error
                error: "Token inválido o expirado"
                code: 401

    NotFound:
      description: Recurso no encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            UserNotFound:
              value:
                status: error
                error: "Usuario no encontrado"
                code: 404
            PetNotFound:
              value:
                status: error
                error: "Mascota no encontrada"
                code: 404

    ValidationError:
      description: Error de validación en los datos
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            InvalidEmail:
              value:
                status: error
                error: "Formato de email inválido"
                code: 400
            MissingFields:
              value:
                status: error
                error: "Campos obligatorios faltantes"
                code: 400

  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: "error"
        error:
          type: string
          example: "Descripción del error"
        code:
          type: integer
          example: 400